#!/usr/bin/env bash

export APP_PORT=${APP_PORT:-8080}
export MYSEL_PORT=${DB_PORT:-3306}
export MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}
export MYSQL_DATABASE=${MYSQL_DATABASE:-styde}
export MYSQL_USER=${MYSQL_USER:-styde}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}

COMPOSE="docker-compose"
# crear variable para determinar
# si docker-compose está en ejecución
PSRESULT=$(docker-compose ps -q)

# Crear variable para ejecutar contenedores existentes
if [ ! -z "$PSRESULT" ]; then
    EXEC="yes"
else
    EXEC="no"
fi

if [ $# -gt 0 ]; then

    # justo después de verificar si tenemos argumentos
    # verificamos si existe el archivo .env y si es así
    # cargamos todas las variables definidas en él
    if [ -f .env ]; then
        source .
    fi

    if [ "$1" == "art" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            app \
            php artisan "$@"

    elif [ "$1" == "composer" ]; then
        shift 1
        # si docker-compose está en ejecucion
        # reutilizamos el contenedor
        if [ "$EXEC" == "yes" ]; then
            $COMPOSE exec \
                app \
                composer "$@"
        # si docker-compose no está en ejecución
        # creamos un contenedor nuevo
        else
            $COMPOSE run --rm \
                -w /var/www/html \
                app \
                composer "$@"
        fi

    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            app \
            ./vendor/bin/phpunit "$@"

    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            npm "$@"

    elif [ "$1" == "gulp" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            ./node_modules/.bin/gulp "$@"

    elif [ "$1" == "yarn" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            yarn "$@"

    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi